"""Update QuizAttempt model

Revision ID: 4c78f2d88a82
Revises: 
Create Date: 2024-12-28 20:06:59.043386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c78f2d88a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint('quiz_attempt_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('selected_answer')
        batch_op.drop_column('question_text')
        batch_op.drop_column('is_correct')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('question_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('selected_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time_taken', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correct_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('quiz_attempt_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('total_questions')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
