"""rename quiz_history column to _quiz_history

Revision ID: 806d3485a468
Revises: c13a89d02f07
Create Date: 2025-01-02 00:45:56.419462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806d3485a468'
down_revision = 'c13a89d02f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_quiz_history', sa.JSON(), nullable=True))
        batch_op.drop_column('quiz_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_history', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('_quiz_history')

    # ### end Alembic commands ###
