"""Add quiz_history column to quiz_attempt

Revision ID: d9683dc6f6c9
Revises: db7e6abde6e4
Create Date: 2024-12-28 20:45:07.581159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9683dc6f6c9'
down_revision = 'db7e6abde6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_column('quiz_history')

    # ### end Alembic commands ###
