"""Add not null constraints and defaults

Revision ID: db7e6abde6e4
Revises: 78bc74c3182e
Create Date: 2024-12-28 20:16:23.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7e6abde6e4'
down_revision = '78bc74c3182e'
branch_labels = None
depends_on = None


def upgrade():
    # Update existing NULL values to 0
    op.execute("UPDATE quiz_attempt SET score = 0 WHERE score IS NULL")
    op.execute("UPDATE quiz_attempt SET total_questions = 0 WHERE total_questions IS NULL")
    op.execute("UPDATE quiz_attempt SET grade = 1 WHERE grade IS NULL")
    op.execute("UPDATE quiz_attempt SET category = 'unknown' WHERE category IS NULL")
    op.execute("UPDATE quiz_attempt SET subcategory = 'unknown' WHERE subcategory IS NULL")
    op.execute("UPDATE quiz_attempt SET difficulty = 'unknown' WHERE difficulty IS NULL")

    # Add NOT NULL constraints
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
