"""rename _quiz_history column to quiz_history

Revision ID: rename_quiz_history_column
Revises: 806d3485a468
Create Date: 2024-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'rename_quiz_history_column'
down_revision = '806d3485a468'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('_quiz_history',
                            new_column_name='quiz_history',
                            existing_type=postgresql.JSON(astext_type=sa.Text()),
                            existing_nullable=True)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('quiz_history',
                            new_column_name='_quiz_history',
                            existing_type=postgresql.JSON(astext_type=sa.Text()),
                            existing_nullable=True) 